### ISSUE TITLE
Customize interpolation

### ISSUE THREAD

**Issue by tehmaestro** [ember-intl/ember-intl#1066]
- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 3.3.0
- Ember CLI Version: 3.3.0
- Ember Intl Version: 4.2.2
- Browser(s): Chrome
- Node Version: 8

### Steps to Reproduce
Hi, I was wondering if there is any way I can customize the interpolation system? I want to use `%@`

**Comment by buschtoens** [comment]
I would advise against this, since ember-intl purposefully follows the [ICU message syntax](http://userguide.icu-project.org/formatparse/messages) standard, which allows for more than just simple interpolation.

Anyhow, to answer your question, there are two main ways you could do it: Either you customize the [translation build pipeline](https://ember-intl.github.io/ember-intl/docs/advanced/addon-support#advanced-usage-treefortranslations-), so that `%@ ` is replaced with `{...}` at build time, or you customize the `intl` service to do that substitution.

**Comment by tehmaestro** [comment]
Thank you. I'm going to close this.
