### ISSUE TITLE
Collaborate with ember-i18n / ember-cli-i18n

### ISSUE THREAD

**Issue by acorncom** [ember-intl/ember-intl#109]
Howdy, saw your extension recently.  It looks like there are some nice parts to it that aren't yet nicely handled in the Ember ecosystem (all the formatters especially).  However, other parts seems to overlap to different degrees with ember-i18n and ember-cli-i18n.  Would it be possible for you guys to collaborate with @jamesarosen / @bcardarella to end up with one awesome add-on?

@jamesarosen is working on v4.0 of his add-on and expressed willingness to discuss things here: https://github.com/jamesarosen/ember-i18n/pull/211#issuecomment-103727431

And there has been discussion of working together between the other two extensions over the last 5 months or so here: https://github.com/dockyard/ember-cli-i18n/issues/56

Thanks, look forward to seeing how this might go!

**Comment by jasonmit** [comment]
I stumbled upon the restart-cli PR over the weekend after seeing a tweet about it and noticed how closely the two projects are organically aligning and was also considering to reach out to @jamesarosen -- so thanks for taking the initiative :)

I'm all in favor of merging the two projects together to focus on building one solution.  Right now, I'm the sole maintainer of the project and have been actively looking for others to join in on the effort of making an approachable internationalization addon.

**Comment by stefanpenner** [comment]
> I'm all in favor of merging the two projects together to focus on building one solution. Right now, I'm the sole maintainer of the project and have been actively looking for others to join in on the effort of making an approachable internationalization addon.

:+1:

**Comment by thoov** [comment]
:+1:

**Comment by acorncom** [comment]
:+1:

**Comment by jamesarosen** [comment]
@jasonmit what do you see as the key distinctions between this any my [v4.0-alpha proposal](https://github.com/jamesarosen/ember-i18n/pull/213)?

Some background: I enumerated some of the [core differences](https://github.com/dockyard/ember-cli-i18n/issues/56) between ember-i18n and ember-cli-i18n a while back. Here's how I addressed those differences in v4:

 * ordered vs named interpolations: I stuck with named interpolations, but made it easy to swap in a custom compiler.
 * rerendering when the locale changes: I adopted ember-cli-i18n's use of `Stream`s. Unfortunately, that's still a private API. At least it's well isolated.
 * globals vs ES6 modules: I adopted ES2015, which is the standard for ember-cli addons
 * HTML safety: the default compiler treats interpolations as unsafe by default and emits safe strings by default. Again, the custom compiler can easily change this
 * locales in modules: I adopted ember-cli-i18n's idea of named packages, though the location of those is slightly different. I built on this idea, adding a `config.js` that can declare custom pluralization and RTL behavior. One thing I haven't yet figured out is how to break a translation set up by pod.
 * Ember support matrix: v4 abandons support for non-ember-cli apps and for earlier v1.x apps. **None** of our three projects yet support glimmer because of emberjs/ember.js#11080

**Comment by jasonmit** [comment]
Just spit balling the differences I see as of now.

Differences:
* Message formatting leverages the [ICU Formatting Message Syntax](http://userguide.icu-project.org/formatparse/messages)
* Ember-intl leverages the Intl API.
  * Implemented natively on firefox and chrome, not safari.  In the case of browsers which don't implement Intl, we provide the Intl polyfil in the assets folder for consumers to inject into their app
  * Intl API used for formatting of Date, Time, and Numbers
* format-message, format-time, format-date, format-number, format-relative helpers and related service methods
  * format-message can contain segments of the string which are time, date, number, relative
* Translations stored in the root folder `/translations` outside of app in ember-intl and are in json format and will soon also support yaml.  I found this to be more friendly for translators and translation services.
* Pluralization rules are dictated by `formatjs-extract-cldr-data` which under the hood uses `node-cldr`
  * We did this to minimize the payload we were sending to the client by stripping out the extract cruft that node-cldr was providing
* ember-intl can be used by non-ember-cli apps.  Though this feature is not documented and currently only used to support adding examples into www.formatjs.io, which is a React app
* Translation lookups are not baked into the translation helper, instead depends on the subexpression `intl-get` to handling to lookup.
```js
{{format-message (intl-get 'messages.product.info')
    product='Apple watch'
    price=200
    deadline=yesterday}}
```

Similarities:
* Formatting of messages (though formatted very differently)
* Helper based
* Injectable service
* Ember-intl is an addon, ember-i18n will be shortly
* Changing locales causes helpers to rerender on both
* ES6 modules
* HTML Safety.  For ember-intl, if you actually want to render a message which contains html you use the format-html-message helper.  Otherwise, everything is properly escaped.
* Both support pushing translations at runtime to a locale

**Comment by jamesarosen** [comment]
Those differences seem pretty *substantial*.

 * The ICU message syntax is a *huge* departure from anything I've ever seen on any project. Ember-i18n is meant to be compatible with the Rails way of doing internationalization so that people can easily share translations between their Rails API and Ember app. Ember-cli-i18n uses Ember's on `fmt` style of ordered interpolations. I suppose ember-i18n could include an alternate ICU compiler that people could swap in. Or it could include a Broccoli task that compiled ICU to JSON (see below). I've worked on a *very* large translation project and I know the value of supporting whatever format the external translation software uses; if ICU is common, it's worth supporting. (It also allows interpolation based on things like gender of subject, which ember-i18n and Rails's I18n don't. [tr8n](https://github.com/berk/tr8n), which I also like, does.)
 * I like the idea of using a native API and polyfill. The [docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl) talk about string comparison and number- and date-formatting -- none of which ember-i18n does.
 * "Translations stored in the root folder translations, outside of app, and are in json format (soon also yaml). I found this to be more friendly for translators and translation services." I get the benefit to external tooling, but the Ember Container seems ideally suited to looking up translations. I guess we could have a Broccoli task that compiles `translations/en.json` as if it were `app/locales/en/translations.js` sort of like what [broccoli-cldr](https://github.com/yahoo/ember-intl/blob/master/lib/broccoli-cldr.js) does.
 * "Pluralization rules are dictated by formatjs-extract-cldr-data which under the hood uses node-cldr." I like the idea of automatically extracting pluralization information from the CLDR -- it's much less error-prone than my manual process. I don't yet understand when that's happening, though. Is it part of your process as the addon developer? Or do apps do that on build via `broccoli-cldr`?
 * "At build time, we determine of the translations which do we need the CLDR rules for instead of bringing over all rules." I like this idea, but I don't know how you implement it. The README doesn't specify how to configure the list. If you try to guess from the `translations/` folder, what if the app uses a translations API?
 * "Translation lookups are not baked into the format-message helper, instead depends on the subexpression intl-get to handling to lookup. This allows for you to pass string literals to format-message." That seems like more work than is needed. I'm probably missing an important use-case -- like "pass string literals to `format-message`". (I also designed ember-i18n at a time when subexpressions didn't exist, so this implementation *couldn't* have occurred to me!)

Overall I think there's a decent chance we could find some ways to collaborate. Some ideas:

 * build a set of broccoli tasks as an external library and share them
 * bring some of the more advanced features (e.g. format-number, ICU message format) from ember-intl into ember-i18n
 * rework into two projects: ember-i18n-translations (which just has the equivalent of your format-message and one or more compilers) and ember-i18n-formatting (which has the Intl polyfill, format-number, etc.)

**Comment by jasonmit** [comment]
>  I like this idea, but I don't know how you implement it. The README doesn't specify how to configure the list. If you try to guess from the translations/ folder, what if the app fetches translations at runtime from an API?

There is no configuration needed.  At build time I walk the translation directory and since the translations are named with the locale name, I know what translations the application is attempting to target.  So I extract all the CLDR info I need and programmatically create them in the app tree's `locales`.  They end up in app.js, but never in the project structure.

I believe it's possible where we can support both translation syntax.  I would prefer we attempt this before we opt for splitting ember-i18n into formatting and translations.

> I don't yet understand when that's happening, though. Is it part of your process as the addon developer? Or do apps do that on build via broccoli-cldr?

Yup, the broccoli plugin takes case of this

> That seems like more work than is needed.

Possibly.  It just allows format-message to be used w/o a translation key.  Something I am opened to revisiting.  There is a discussion around this on `react-intl`, I'll try and dig it up today.

**Comment by jamesarosen** [comment]
I just saw [formatjs](http://formatjs.io/). Among other things, they have an ICU parser that we could use in translating from ICU to ES6 modules that export objects -- compatible with Ember's resolver.

**Comment by jamesarosen** [comment]
(I had been assuming that users of this project shipped ICU to the browser. I didn't realize that the parent project was also a Node ecosystem.)

**Comment by jasonmit** [comment]
> we could use in translating from ICU to ES6 modules that export objects

I am a little lost here, could you explain?  You would like to "precompile" the ICU messages to an AST which gets exported as an es6 module?  Currently I don't precompile the ICU message and just pass it as a string to the message parser.  The translation files themselves I would prefer not be ES6 modules, it's something I currently do in 1.x of ember-intl but was moving away from in 2.0 for reasons I stated above.

**Comment by jamesarosen** [comment]
> I am a little lost here, could you explain?

We precompile Handlebars templates with a Broccoli plugin because shipping the Handlebars compiler and doing parsing in the browser is expensive. Ember-I18n ships with a very small, fast compiler for in-browser compilation. Additionally, it uses container lookup for the translations and doesn't do anything if they're already functions; that way, you can precompile translations in your build process and avoid compilation in the browser altogether.

So I don't really care what format the files are in on disk. ICU files sounds fine to me. The idea would be to have a Broccoli plugin that converts those into JS modules that the container can recognize.

Thus

```icu
// app/locales/en/translations.icu
You have {itemCount, plural,
    =0 {no items}
    one {1 item}
    other {{itemCount} items}
}.
```
might become
```js
define('my_app/locales/en/translations', ['exports'], function (exports) {
  'use strict';

  exports['default'] = {
    "You have {itemCount} items.": {
      zero: "You have no items."
      one: "You have one item."
      other: "You have {{itemCount}} items."
    }
  };
});
```
or possibly
```js
define('my_app/locales/en/translations', ['exports'], function (exports) {
  'use strict';

  exports['default'] = {
    "You have {itemCount} items.": {
      zero: function() { return 'You have no items.'; }
      one: function() { return 'You have one item.'; }
      other: function(scope) { return 'You have ' + scope.itemCount + ' items.'; }
    }
  };
});
```

**Comment by jasonmit** [comment]
Ah-ha.  So how I handle this currently is the user constructs a JSON/YAML translation file and pass the key of the translation to format-message (or `t` in your case) helper.  At build time this becomes an ES6 module which I do lookups against to resolve the translation.

We could optimize this a bit so that if the user inlines a translation we move this to the default translation module instead (the default is the fallback for any translations where the keys are not found on the "active" locale - this merging of translation object also happens at build time in 2.0).

But we might instead want to warn on this because it defeats the purpose of internationalization if you're hardcoding string literals in your templates.

**Comment by jamesarosen** [comment]
In a template in the README you have `intl-get 'messages.product.info'`. Currently, the source for that is
```js
// app/locales/en.js
import Locale from 'ember-intl/models/locale';

export default Locale.extend({
    messages: {
        product: {
            info: '{product} will cost {price, number, EUR} if ordered by {deadline, date, time}'
        }
    }
});
```
It seems like that would convert straightforwardly to YAML:
```yml
messages:
  product:
    info: "{product} will cost {price, number, EUR} if ordered by {deadline, date, time}"
```
What would that look like if it had several nested ICU variants?

**Comment by jasonmit** [comment]
> In a template in the README you have intl-get 'messages.product.info'. Currently, the source for that is

You got it and the move in 2.0 to JSON/YAML just means that same ES6 module gets constructed at build time.

> What would that look like if it had several nested ICU variants?

Hopefully I understood your question, but it would be this:
```yaml
messages:
  product:
    info: "{product} will cost {price, number, EUR} if ordered by {deadline, date, time}"
    name: "Apple Watch"
    cost: "{price, number, EUR}"
```
```hbs
{{format-message (intl-get 'messages.product.info')}}
{{format-message (intl-get 'messages.product.name')}}
{{format-message (intl-get 'messages.product.cost')}}
```

**Comment by jamesarosen** [comment]
Actually, I meant things like the variants and rules for "Amy invited {numGuests} guests to [his/her/hir/their] party."

**Comment by jasonmit** [comment]
Ah, I would use `select` for that: http://userguide.icu-project.org/formatparse/messages

**Comment by jamesarosen** [comment]
Right. I'm wondering what that looks like in the YAML. Is it
```yml
event:
  invited_to_party: >
    "{gender_of_host, select, "
      "female {"
        "{num_guests, plural, offset:1 "
          "=0 {{host} does not give a party.}"
          "=1 {{host} invites {guest} to her party.}"
          "=2 {{host} invites {guest} and one other person to her party.}"
          "other {{host} invites {guest} and # other people to her party.}}}"
      "male {"
        "{num_guests, plural, offset:1 "
          "=0 {{host} does not give a party.}"
          "=1 {{host} invites {guest} to his party.}"
          "=2 {{host} invites {guest} and one other person to his party.}"
          "other {{host} invites {guest} and # other people to his party.}}}"
      "other {"
        "{num_guests, plural, offset:1 "
          "=0 {{host} does not give a party.}"
          "=1 {{host} invites {guest} to their party.}"
          "=2 {{host} invites {guest} and one other person to their party.}"
          "other {{host} invites {guest} and # other people to their party.}}}}"
```

**Comment by jasonmit** [comment]
Yup, just minor touchup to the multiline string.

```yaml
event:
  invited_to_party: >
    {gender_of_host, select,
      female {
        {num_guests, plural, offset:1 
          =0 {{host} does not give a party.}
          =1 {{host} invites {guest} to her party.}
          =2 {{host} invites {guest} and one other person to her party.}
          other {{host} invites {guest} and # other people to her party.}}}
      male {
        {num_guests, plural, offset:1 
          =0 {{host} does not give a party.}
          =1 {{host} invites {guest} to his party.}
          =2 {{host} invites {guest} and one other person to his party.}
          other {{host} invites {guest} and # other people to his party.}}}
      other {
        {num_guests, plural, offset:1 
          =0 {{host} does not give a party.}
          =1 {{host} invites {guest} to their party.}
          =2 {{host} invites {guest} and one other person to their party.}
          other {{host} invites {guest} and # other people to their party.}}}}
```

**Comment by jamesarosen** [comment]
Can we precompile that all the way into something like the following?
```js
export default {
  'event.invited_to_party': function(context) {
    if (context.gender_of_host === 'female') {
      if (context.num_guests === 0) { return context.host + ' does not give a party.'; }
    // ...
  }
};
```
We'd need to augment `context` with things like `{ num_guests__inflection: 'other' }` or something similar.

**Comment by jasonmit** [comment]
What are the advantages of this precompiling approach?  I know we can precompile it to the message format AST: https://github.com/yahoo/intl-messageformat-parser

**Comment by jamesarosen** [comment]
> What are the advantages of this precompiling approach?

I see a few:

 * **Smaller `vendor.js`**. We don't need to send compiler code over the wire.
 * **Faster boot**. We don't need to run compilation in the browser.
 * **More flexible**. If people want to use some other translation format, the only *runtime* requirement is that the `locales/en/translations` package exports a hash of functions.

**Comment by jasonmit** [comment]
The disadvantage is a much larger translation file, that is the only push back.  Maybe @ericf has put some thought into this, I'll ping him for some feedback.

**Comment by jamesarosen** [comment]
@ebryn has been doing some I18n work where he actually compiles fully translated templates in the build process. You end up with a version of the app for each locale. The inflection logic actually goes in the compiled template directly. I'm not sure how that affects file size exactly.

**Comment by lmcardle** [comment]
> I'm all in favor of merging the two projects together to focus on building one solution.

:thumbsup:

**Comment by skyuplam** [comment]
> I'm all in favor of merging the two projects together to focus on building one solution.
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by tim-evans** [comment]
I'm currently working on adding localizations to an app. Is there any particular addon that I should go "in" on in each of the authors opinions. I would like to make an informed decision rather than use a  :crystal_ball:.

**Comment by jasonmit** [comment]
@tim-evans all I can say is evaluate both.  They both offer something slightly different in terms of what they're capable of formatting and the flexibility of the formatting.  The goal of the consolidation would be to keep the feature set of both projects intact and merge anything that overlaps.

**Comment by tim-evans** [comment]
@jasonmit Thanks for the quick response :)

I've evaluated both in the past, and ended up using I18n.js and writing an ember-addon myself. I will denote there that it will be deprecated. My only hope is that nice `{{l}}` and `{{t}}` helpers may grace my handlebars templates.

**Comment by jasonmit** [comment]
T helper is format-message and L is format-time.  Are there any features missing that you we're looking for?

**Comment by tim-evans** [comment]
The API is a bit clumsy to use in JS. I'd love if it was easier to translate things there. I'm currently grabbing the service, and jumping through a few hoops to get the message value, then translating it. Although, I'm not sure if I can simply use the Intl API. If I can, then all I'll say is that it's a tad clumsy to use :)

**Comment by jasonmit** [comment]
Ah the clumsy part being intl-get?  Curious since I would like to address whatever the turn off is

**Comment by tim-evans** [comment]
Yup! That's the part

**Comment by Truffula** [comment]
I'll second @tim-evans on this - I tried converting to ember-intl for some of the additional locale features, being accustomed to being able to just call `Ember.I18n.t('path.to.translation')` from anywhere in JS, (without depending on an injected service for a plain `Ember.Object`), or `{{t 'path.to.translation'}}` anywhere in the templates - including inline, e.g. `{{foo bar=(t 'path.to.foo.bar')}}`. The vast majority of my translations don't have any variables, so the simpler the API (and the string files) the better.

**Comment by jasonmit** [comment]
I propose then to implement treating the argument of format-message as a path and in the case you want to inline your ICU string you wrap it in a `literal` helper.

```hbs
{{format-message 'path.to.foo.bar'}}
{{format-message literal('{{population, number, integer} as of {census_date, date, long}}')}}
```

**Comment by tim-evans** [comment]
I like this approach :)

And just for some insight into how I was translating strings at my last gig, I ended up using a helper that joined strings together for anything that was dynamic. For example:

```handlebars
{{t (join 'product.categories.' product.category)}}
```

**Comment by jasonmit** [comment]
@tim-evans I should have 2.0 finished in the next day or two and it will contain what I proposed above.

**Comment by tim-evans** [comment]
Super! Excited for this :)

**Comment by caridy** [comment]
about this:

```
{{format-message 'path.to.foo.bar'}}
{{format-message icu('{{population, number, integer} as of {census_date, date, long}}')}}
```

when we first tried this, we decided to drop it (in plain handlebars) due to the ambiguity associated with it. What should ICU return? obviously not an string, but an object with some specific signature that you don't know. This makes this more complicated to understand, and less flexible. What if I don't want to use `icu()` and I don't want to use path? what should I do then? /cc @ericf

**Comment by jasonmit** [comment]
> What if I don't want to use icu() and I don't want to use path? what should I do then?

@caridy if you're not passing a path or an ICU string then what are you passing?  I can only think of a case where you are both one or the other.  If you need to do something you could likely invoke the service method directly to format message strings.  `this.intl.formatMessage(str, ...args);`  The service method for formatting a string will continue to expect an ICU string.

The ultimate goal in this change is to align with a similar syntax to ember-i18n.  The first major thing to is to align the helper APIs, alias `format-message` to `t` and make paths the default value.

**Comment by elwayman02** [comment]
Any updates on plans to move forward with merging ember-intl and ember-i18n?

**Comment by jasonmit** [comment]
ember-intl now support the same helper syntax, `{{t 'some.key'}}` and a very similar service API as ember-i18n.  Everything else ember-intl supports is additive at this point and buy in from @jamesarosen  is needed in order to bring these features over (YAML/JSON support, Intl API, date/time + number + relative formatting, and ICU message syntax).  Most of which will be optional and driven by configuration so consumers can opted out.

**Comment by GCheung55** [comment]
>The disadvantage is a much larger translation file, that is the only push back.

There's basically two scenario's right?

* Precompile translation file + vendor.js.
* Regular translation file + vendor.js + compiler.

At the outset, it is likely that a translation file is significantly smaller than the vendor.js with/without the compiler. As an application grows, the translation file is likely to increase. At some point it will be larger than the vendor.js with/without the compiler. If that point becomes a reality for the application then it would be beneficial to have the translation file to be compiled at runtime instead.

Perhaps consider why are Handlebars/HTMLbars templates precompiled?

Could precompiling be an option?

**Comment by jasonmit** [comment]
Since this is being asked for by a few people now, I'll scope out how much work would be involved in switching to something that has built-in precompiling support:  https://github.com/SlexAxton/messageformat.js

Hopefully then we can move forward on an integration plan.

**Comment by jasonmit** [comment]
Work has begun to allow for the compiler to be swappable
https://github.com/jasonmit/ember-intl/issues/350

This is loosely related, as the work needs to happen in some form.

**Comment by jamesarosen** [comment]
@jasonmit I've been playing around with moving the compiler to compile-time instead of runtime. A lot of the "translation lookup" logic then becomes just a property-lookup.

**Comment by jasonmit** [comment]
@jamesarosen I'm interested to hear about this.  Is this in relation to an ICU?  I wonder it could be done in a way that allows for another compiler to be provided.  Would you be able to still support the runtime scenario for those lazy-loading translations?

**Comment by edeis53** [comment]
@jamesarosen @jasonmit with your plans to merge ember-intl and ember-i18n at some point, which project is more appropriate for use to start development on a new application?

**Comment by jasonmit** [comment]
@edeis53 unsure when and if that will happen.  No movement has happened in that direction.  I've started to position ember-intl to optionally handle the same translation syntax as ember-i18n.  ICU message syntax will remain the default.

I would compare both, as they have different features, to see which one satisfies your needs now and into the future.

**Comment by jasonmit** [comment]
But to be clear, I wish it they did merge and if that does happen I can assure you no features currently supported will be dropped in that transition.  Which is why I say choose which one best fits your needs.

**Comment by Turbo87** [comment]
> switching to something that has built-in precompiling support: https://github.com/SlexAxton/messageformat.js

that looks interesting actually... certainly worth investigating whether that gains us any speed/filesize improvements

**Comment by cicoub13** [comment]
👍

**Comment by jamesarosen** [comment]
https://github.com/jamesarosen/ember-i18n/issues/481

**Comment by jasonmit** [comment]
Closing as this is being handled by ember-i18n and the community.
