### ISSUE TITLE
Fail tests/CI on missing translations?

### ISSUE THREAD

**Issue by lolmaus** [ember-intl/ember-intl#1170]
There are two cases:

* A translation is missing during a test. I would like that test to fail.
* Some of the translation files are missing entries present in other translation files. I would like either `ember t` to fail or have a distinct terminal command that would exit with an error code in case of missing translations.

How do I do that? Not sure if it's a documentation issue or a missing feature.

**Comment by jasonmit** [comment]
> A translation is missing during a test. I would like that test to fail.

You can implement your own custom behavior for what happens when a translation is missing:
https://ember-intl.github.io/ember-intl/versions/master/docs/guide/missing-translations

Your implementation of this method would check if Ember is in a testing env and if so, throw, else return a string of your liking.

> Some of the translation files are missing entries present in other translation files. I would like either ember t to fail or have a distinct terminal command that would exit with an error code in case of missing translations.

https://ember-intl.github.io/ember-intl/versions/master/docs/guide/missing-translations#throwing-a-build-error-on-missing-required-translation

Should achieve what you're describing.

**Comment by lolmaus** [comment]
@jasonmit Thank you for your explanations, this indeed resolves my issues! 🙏

**Comment by lolmaus** [comment]
СС @nickschot @simonihmig
