### ISSUE TITLE
Bundle size regression in v6.2.0

### ISSUE THREAD

**Issue by jelhan** [ember-intl/ember-intl#1800]
v6.2.0 seem to dramatically increase the bundle size of a consuming application.

I noticed it by an app, which uses [`ember-cli-bundlesize`](https://github.com/kaliber5/ember-cli-bundlesize) in CI pipeline. The bundle size test started failed in the upgrade from 6.1.2 to 6.2.0:

```
> ember bundlesize:test

Building for production...
not ok 1 - app:javascript: 329.21KB > 310KB (gzip)
ok 2 - app:css: 16.09KB <= 16.5KB (gzip)
Bundlesize check failed with 1 error!
```

App JavaScript was 306KB in a recent pipeline for main branch. Seems that ember-intl v6.2.0 increases it by more than 23KB.

The affected app is open source. Please find the PR upgrading ember-intl from 6.1.2 to 6.2.0 here: https://github.com/jelhan/croodle/pull/758

**Comment by ijlee2** [comment]
@jelhan Thanks for reporting the rather large increase in bundle size. I'm surprised because I removed two dependencies in `6.2.0`, and `npm` shows a decrease in the number of files and in the unpacked size by 5kB.

I can think of a couple of possibilities:

- The dependencies updated in #1797
- The refactoring in #1798 (removing a base function to fix TS errors and improve code readability)

The latter has to do with test helpers, which shouldn't affect the production build. To check the former, can you use npm overrides to pin the `ember-intl`'s dependencies to the latest version?

<img width="900" alt="" src="https://github.com/ember-intl/ember-intl/assets/16869656/818615d8-8470-4fc3-a39d-f1a3c3be49b1">

**Comment by ijlee2** [comment]
Hi, @jelhan. Have you had a chance to look at updating `@formatjs/*` and `intl-messageformat` to the latest, to see if this reduces the bundle size?

**Comment by jelhan** [comment]
> Please try updating `ember-intl` to `v6.2.2`.

v6.2.2 fixed it. CI passed, which failed for bundle size check before. Thanks a lot for fixing!
