### ISSUE TITLE
Basic usage results in: You attempted to update `_locale` [...] infinite revalidation bugs, and performance issues, and is not supported.

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-intl/ember-intl#1826]
I've seen: https://github.com/ember-intl/ember-intl/issues/1659

But the issue seems unresolved.

Issue is easily reproducible.

Error:
```
 Uncaught Error: Assertion Failed: You attempted to update `_locale` on `<IntlService:ember74>`, but it had already been used previously in the same computation.  Attempting to update a value after using it in a computation can cause logical errors, infinite revalidation bugs, and performance issues, and is not supported.

`_locale` was first used:

- While rendering:
  -top-level
    application
```
where the application template is:
```hbs
{{format-message "hi there {boop}" boop="me"}}
```

- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

```bash
❯ pnpm ls ember-source ember-cli ember-intl

devDependencies:
ember-cli 5.5.0
ember-intl 6.4.0
ember-source 5.5.0
```

- Browser(s): n/a
- Node Version: n/a

### Steps to Reproduce

Repro repo: https://github.com/NullVoxPopuli/ember-intl-reproduction-backtracking-assertion-when-accessing_local

```bash
npx ember-cli@latest new my-app --pnpm --embroider
cd my-app
ember install ember-intl
echo '{{format-message "hi there {boop}" boop="me"}}' > app/templates/application.hbs
pnpm start
# visit localhost:4200, pop open the console and see the error
```

**Comment by Windvis** [comment]
We're also running into this. We use ember-intl in an addon and allow apps to set the prefered language, if they don't want the default. But after the 6.1+ update apps are forced to set the language because of this error, even if they want the default. We could work around this by injecting and accessing the service somewhere in the addon code before the render happens, but that's obviously not ideal.

Some quick debugging points me to this line: 
https://github.com/ember-intl/ember-intl/blob/701e0806be06ed484d7c4030b2f53b2cc251b7b0/ember-intl/addon/services/intl.js#L108

If the `this.locale` access is removed the error disappears. I think we can safely remove that, since it can never not be something else than `null` at this point in the constructor AFAIK?

**Comment by Windvis** [comment]
Looking further, it seems to be caused by the `@dependentKeyCompat` decorator: https://github.com/ember-intl/ember-intl/blob/701e0806be06ed484d7c4030b2f53b2cc251b7b0/ember-intl/addon/services/intl.js#L50

After accessing `this._locale` directly or removing `dependentKeyCompat` from the getter the error isn't triggered either.

(I still think we can simply remove the locale access at that point, since it will always be `null`.)

**Comment by ijlee2** [comment]
I replied to @Windvis' question [on Discord](https://discord.com/channels/480462759797063690/1209140251046715423/1209811176331018300).

**Comment by ijlee2** [comment]
I think we can ignore the originally reported issue, because [`this.intl.setLocale(['en-us'])` hadn't been called in the app's `application` route](
https://github.com/NullVoxPopuli/ember-intl-reproduction-backtracking-assertion-when-accessing_local/commit/0c8239984348100a15aeef022e8eb4deaec63c99).

<img width="900" alt="" src="https://github.com/ember-intl/ember-intl/assets/16869656/fb7d64bf-be5a-4422-b997-d86bd660be3a">

I tried out @Windvis's approach of removing `@dependentKeyCompat` in #1843. I think this can help us fix the issue of `You attempted to update _locale`, where rendering and unit tests without `setupIntl()` would error starting `ember-intl@v6.1.0`.

I suspect that `@dependentKeyCompat` had been added to support [macros](https://github.com/ember-intl/ember-intl/tree/v6.5.1/packages/ember-intl/addon/macros) (to be removed in `ember-intl@v7.0.0`), so we can't merge #1843 at the moment.
