### ISSUE TITLE
Do not blow up the whole page if a variable is missing ?

### ISSUE THREAD

**Issue by gzurbach** [ember-intl/ember-intl#1853]
This issue happens to me all the time and I wonder if it should be that way.

If I declare a string that contains a variable, but for any reason the variable is not provided, `ember-intl` throws an error and the entire rendering of the page breaks:

```
The intl string context variable "firstName" was not provided to the string "Hello {firstName}"
```

I can see the behavior being desirable in development builds, but in production? It seems overkill. A simple warning would be enough.

We handle 13 locales and download translations asynchronously, which can sometimes result in out-of-sync translations lasting for several days. Consider a scenario where we make a code change to eliminate a variable from a string. We are unable to deploy the change until that variable has been removed from every locale. Otherwise, the page won't render properly in any language where that variable remains present.

Is that something we could consider changing?

**Comment by ijlee2** [comment]
Hi, @gzurbach. Thanks for providing your feedback. The error message is [coming from `@formatjs/intl-messageformat`](https://github.com/formatjs/formatjs/blob/intl-messageformat%4010.5.11/packages/intl-messageformat/src/error.ts#L57-L65).

In `ember-intl@6.5.0` and above, you can patch the file `addon/-private/utils/formatjs.ts` (in particular, the function `onFormatjsIntlError()`) so that your case is addressed:

```diff
export function onFormatjsIntlError(error: IntlError): void {
  switch (error.code) {
+     case IntlErrorCode.FORMAT_ERROR: {
+       // Do nothing
+       break;
+     }
+ 
    case IntlErrorCode.MISSING_TRANSLATION: {
      // Do nothing
      break;
    }

    default: {
      throw error;
    }
  }
}
```

If you are on a version between `6.1.0` and `6.4.1`, you can find the corresponding code in `addon/services/intl.js` (i.e. patch this file instead). For example, https://github.com/ember-intl/ember-intl/blob/v6.4.1/ember-intl/addon/services/intl.js#L132-L136.

**Comment by gzurbach** [comment]
Thank you for your thorough response, @ijlee2. I appreciate it. I should clarify that I am currently running `ember-intl@6.5.3`.

I prefer not to resort to cloning or branching the library for this particular issue. My intention in reaching out was more of a suggestion for potential inclusion in a future version of `ember-intl`.

The proposal:

- For development builds: throw any `FORMAT_ERROR`.
- For production builds: consider displaying a warning or gracefully ignoring the error.

Thank you for your consideration!
