### ISSUE TITLE
Vulnerability in dependency `glob-parent` via `broccoli-merge-files`

### ISSUE THREAD

**Issue by ccdexcom** [ember-intl/ember-intl#1858]
- [X] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [X] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: N/A
- Ember CLI Version: N/A
- Ember Intl Version: 6.5.3
- Browser(s): N/A
- Node Version: v20.11.1 (likely N/A)

### Steps to Reproduce
[Example Repo](https://github.com/ccdexcom/pnpm-ember-intl)
1. Create a new node project (folder with root-level `package.json`)
2. `pnpm add ember-intl`
3. `pnpm audit`
4. `glob-parent` listed as a vulnerability
  ```
➜  pnpm-ember-intl git:(main) pnpm audit
┌─────────────────────┬────────────────────────────────────────────────────────┐
│ high                │ glob-parent vulnerable to Regular Expression Denial of │
│                     │ Service in enclosure regex                             │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Package             │ glob-parent                                            │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Vulnerable versions │ <5.1.2                                                 │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Patched versions    │ >=5.1.2                                                │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Paths               │                                                        │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ More info           │ https://github.com/advisories/GHSA-ww39-953v-wcq6      │
└─────────────────────┴────────────────────────────────────────────────────────┘
1 vulnerabilities found
  ```

I've seen #1791 and #1666. I don't think #1791 fixes the root issue we're seeing with `ember-intl`. The `overrides` in #1791 I believe only have an effect on `ember-intl` as a project (cloned locally and installed and with its local lockfiles) but not on projects that use `ember-intl` and their lockfiles ([see example repo](https://github.com/ccdexcom/pnpm-ember-intl)).

There are other vulnerabilities coming in from `fast-glob` via `broccoli-merge-files` but `glob-parent` is an easy one to use as an example because it shows up with the `pnpm audit` command.

Aside from consumers of `ember-intl` doing their own overrides or package installer specific workarounds I think there are two solutions:
1. Try and get `broccoli-merge-files` bumped (https://github.com/buschtoens/broccoli-merge-files/pull/431)
2. Refactor away from `broccoli-merge-files`. Would you be open to a pull request? I'm not sure how much effort would be involved but wanted to check first before going down that path

Maybe there's other solutions we haven't considered? Thanks for all your work in keeping `ember-intl` running.

**Comment by LucasHillDex** [comment]
`broccoli-merge-files` has additional vulnerabilities coming in through [broccoli-test-helper](https://github.com/broccolijs/broccoli-test-helper) so it is the source of quite a few vulnerabilities. Could be nice to get rid of it if it is no longer maintained.

**Comment by LucasHillDex** [comment]
@ijlee2 would you mind taking a look at this proposed fix? https://github.com/ember-intl/ember-intl/pull/1863/

**Comment by ijlee2** [comment]
@LucasHillDex Thanks for working on #1863 and https://github.com/buschtoens/broccoli-merge-files/pull/431.

I will have a look at the former PR (I'll need time to check how the change affects a work project), and can ask for feedback from @buschtoens.

**Comment by ijlee2** [comment]
Hi, @LucasHill. I messaged Jan for feedback. Here's the reply that I received:

> I don’t really have the time & interest to reasonably maintain `broccoli-merge-files`, so I would recommend to migrate off of it. Sorry. :/
>
> Option 2 [Remove the use of `broccoli-merge-files` in `ember-intl`] would be my recommendation. Do you require my help for reviewing it?
>
> I briefly looked at the PR: I can imagine that the removal of intermediary `.json` files will break `ember-intl` for CLARK, as AFAIR we rely on that feature.
>
> I think it should be possible to do a minimal change by really only replacing the usage of `broccoli-merge-files` with manual broccoli plumbing.

So both Jan and I are, in general, in favor of removing unnecessary dependencies from `ember-intl`.

However, because (1) #1864 shows changes to the expected outputs in test files and (2) `ember-intl` currently doesn't check in CI more complex ways of loading translations, such as [writing translations to `dist` folder](https://ember-intl.github.io/ember-intl/versions/v7.0.0-beta.2/docs/guide/asynchronously-loading-translations#writing-translations-to-dist-folder) and [pushing translations into `ember-intl`](https://ember-intl.github.io/ember-intl/versions/v7.0.0-beta.2/docs/guide/asynchronously-loading-translations#pushing-translations-into-ember-intl), I need to go with an approach that will be the least breaking for many Ember projects, not just your team's and mine.

In addition, my perspective on vulnerability reports (e.g. from Dependabot) is similar to that of https://overreacted.io/npm-audit-broken-by-design/: For frontend, they tend to produce many false positives, with little actionable information on how a vulnerability can be exploited in practice (especially, in the context of Ember), not just in theory.

For example, `broccoli-merge-files` indirectly depends on `glob-parent` through `fast-glob`, but [`fast-glob` is used just once to read translation files](https://github.com/buschtoens/broccoli-merge-files/blob/v0.8.0/index.ts#L169-L173). (Here, I may be incorrect, since I'm not too familiar with how `ember-intl` has used `broccoli-merge-files` over the years.)

At work, we use `yarn`'s `overrides` to install `glob-parent@6.0.2`, and this works fine with `ember-intl@6.5.3` and `7.0.0-beta.2`. Therefore, I think asking end-developers to use their package manager to install `glob-parent@6.0.2` is a safer option than merging #1864.

As I mentioned earlier, it will take me some time (about a week) to learn more about `broccoli-merge-files` and try out the proposed change in #1864 against my team's production project. In the meantime, you could help me out by:

- Creating an additional Ember app(s) in the `docs` folder, so that, in CI, we can check that we can continue to (1) push translations into `ember-intl` and (2) write translations to `dist` folder.
- Talking to your security team about considering the risk of `glob-parent` from `ember-intl` to be low. Together, figure out how `fg.stream()` can actually be exploited.

What do you think?

**Comment by LucasHill** [comment]
@ijlee2 thanks for the detailed feedback.

We have certain regulatory requirements that make working with these vulnerabilities more difficult and while I agree there is a great argument for how low the risk is for these vulnerabilities in build tools we are still making an effort to remove them.

I understand now the effect of removing the intermediate json files, my original interpretation was those were thrown out in favor of the final `translations.js` file. I should be able to modify my PR to restore those json files pretty easily. 

Could you tell me a little more of what you'd want with the additional docs app?

**Comment by LucasHill** [comment]
@ijlee2 I updated my [PR](https://github.com/ember-intl/ember-intl/pull/1864) to get back the behavior I had inadvertently removed. If I'm understanding correctly, we need to support the `publicOnly=true` case where the translations get loaded asynchronously rather than being combined into the bundle. Could you let me know if my new approach is right? Is the additional docs app you want to enable tests that the `publicOnly=true` case works?

**Comment by ijlee2** [comment]
@LucasHill For additional docs-apps, let's start with #1866 and #1867, because I'm not sure yet how we could test the `dist` folder easily in CI, when setting `publicOnly` to `true`.

#1866 is easier to complete so I recommend that you start with that one (with create 1 PR per issue). Let me know if you need clarifications and I can reply to you next week.

Thanks,

**Comment by LucasHill** [comment]
@ijlee2 Unfortunately I don't have the bandwidth currently to take on those projects, are they a prerequisite for patching the vulnerability? Do you have concerns my PR as it is now may break compatibility with other projects? To me is looks like the output will be the exact same as it is currently, but I could still be missing some context.
