### ISSUE TITLE
[Feature Request] Add strict mode for setupIntl test hook

### ISSUE THREAD

**Issue by sukima** [ember-intl/ember-intl#1899]
Allow `setupIntl` to have a configuration that will put it into strict mode.

Strict mode will error whenever a translation is performs and it is missing. This will allow running tests and discovering use of `{{t "…"}}` that uses a key that the system doesn't know about. Possible typos and such.

**Comment by ijlee2** [comment]
Hi, @sukima. I didn't understand how your tests currently look, such that you had wanted such a feature. Can you provide me an example of a test that is passing and has a translation key that's not defined in the `translations` folder?

I expect such tests to have a text assertion like this:

```ts
test('it renders', async function (assert) {
  await render(hbs`
    <Hello @name="Zoey" />
  `);

  assert
    .dom('[data-test-message]')
    .hasText('t:hello.message:("name":"Zoey")');
});
```

That is, we see the text `t:hello.message:("name":"Zoey")` because the translation doesn't exist.

It may be possible that your tests use the test helper `t()`, in which case assertions would pass even when the translation doesn't exist. For these kinds of reasons, [I started to recommend not using `t()` in the documentation for `6.4.0`](https://ember-intl.github.io/ember-intl/versions/v7.0.3/docs/test-helpers/t#alternative-approaches).

With `v7`, you can try writing a test helper that calls the `intl` service's [`setOnMissingTranslation()`](https://ember-intl.github.io/ember-intl/versions/v7.0.3/docs/services/intl-part-2#setonmissingtranslation-) and throws an error instead of returning a string. I currently don't think it's a good idea to increase the addon's API to detect missing translations in tests.

**Comment by ijlee2** [comment]
Will close the issue for now.

**Comment by sukima** [comment]
Our system separates the translation key from the translated string. Such that testing a hard coded string would not be helpful. I would also argue that is an incorrect exception in a test anyway. Instead it make more sense to focus on the translation key.

For example, say I have a string that uses some data to properly translate. A test verifying my code properly passes along the data to the component (and thus the translation system) we might have something similar to this:

```js
// foobar: "{count, plural, =1 {A single value} other {Multiple values}}"
assignDataToComponent({ count: 0 });
assert.dom(page.label.element).hasText(t('foobar', { count: 0 });
assignDataToComponent({ count: 4 });
assert.dom(page.label.element).hasText(t('foobar', { count: 4 });
```

In this way translators are free to assign that key to anything they want and the test does not need to be updated. Though there could be alternative patterns this one feels the most natural and tells the story better IMHO. But as you said it does gloss over that if it is missing it won't be caught.

Thinking about this it is arguable that the test in question should not worry about the translation sytem in regards to making sure the key exists or not and instead a separate assertion would be more appropriate in that regard. Perhaps something like `assert.false(t('...', { ... }).startsWith('t:'))` or `assertExists('translation-key')` In this way we know the key exists but we later can test that the use of any dynamic data produces an expected result (what ever a translator felt is the expected result) and remains a separation of concerns between the testing of behavior and the presentation specific implementation.
