### ISSUE TITLE
Import error after updating `@ember/test-helpers` to version `4.x`

### ISSUE THREAD

**Issue by wozny1989** [ember-intl/ember-intl#1916]
### Description:

After updating the `@ember/test-helpers` package to version 4.x, I encountered a build error when trying to build my Ember application that uses ember-intl.

### Steps to reproduce:
 - Update `@ember/test-helpers` to version 4.x.
 - Build the Ember application.
 - The following error occurs:
 ```shell
Build Error (WebpackBundler)

ember-intl tried to import "@ember/test-helpers" in "ember-intl/test-support/add-translations.js" from addon code, but "@ember/test-helpers" is a devDependency. You may need to move it into dependencies.
```

### Expected behavior:
The application should build without errors after updating the `@ember/test-helpers` package.

### Actual behavior:
The build fails due to an improper import of `@ember/test-helpers` from the `ember-intl/test-support/add-translations.js` file. The error message suggests that `@ember/test-helpers` is currently listed as a devDependency, but it is being imported from within addon code, which causes the build to fail.

### Suggested solution:
It seems that `@ember/test-helpers` should be moved from devDependencies to dependencies in the `ember-intl` package's package.json. This would ensure that it is correctly included in production builds.

### Environment:
- Ember Version: ~5.4.x
- Ember CLI Version: ~5.4.x
- Ember Intl Version: ~7.0.5
- Browser(s): Chome
- Node Version: ~20.x

**Comment by ijlee2** [comment]
Hi, @wozny1989. Thanks for reporting the issue.

If I understand the problem right, updating `@ember/string` to `v4` in a consuming project doesn't cause the issue (because `ember-intl` doesn't use `@ember/string` directly), but updating `@ember/test-helpers` to `v4` does. Do you think this assumption is correct?

In #1918, I saw that after updating `@ember/test-helpers`, running `pnpm test` in `tests/ember-intl` reproduces the error message:

```sh
ember-intl tried to import "@ember/test-helpers" in "ember-intl/test-support/add-translations.js" from addon code, but "@ember/test-helpers" is a devDependency. You may need to move it into dependencies.
```

Afterwards, I tried to see if listing `@ember/test-helpers` as a peer dependency would fix the issue. While the error went away, the [CI run](https://github.com/ember-intl/ember-intl/actions/runs/10559412463) indicated that I won't be able to release a new verson of `ember-intl`, because several `ember-try` scenarios failed:

```sh
> test-app-for-ember-intl@1.3.18 test /home/runner/work/ember-intl/ember-intl/tests/ember-intl
> ember test --test-port=0

not ok 1 Chrome 127.0 - [124 ms] - Acceptance | smoke-tests > de-de: We can see translations
    ---
        actual: >
            null
        stack: >
            Error: You must set up the ember-test-helpers environment with either `setResolver` or `setApplication` before running any tests.
```

Until after EmberFest, I won't have time to look into what the error message above means (whether this is a bug in `@ember/test-helpers@4.0.2`) and how else to fix the dependency issue. Maybe you can reach out to the Ember team on Discord for more help?

**Comment by wozny1989** [comment]
@ijlee2 sorry for my mistake! Of course, as you said, the problem exists after updating `@ember/test-helpers` to version 4

**Comment by ijlee2** [comment]
@wozny1989 No problem.

**Comment by ijlee2** [comment]
@wozny1989 Updating `ember-intl` to `7.0.6` or higher should allow you to update `@ember/test-helpers` to `v4`.

**Comment by wozny1989** [comment]
Thanks @ijlee2 and @NullVoxPopuli for your efforts!
