### ISSUE TITLE
Incompatibility between `ember-cli-addon-guard` and `ember-intl` >= `4.2.1`

### ISSUE THREAD

**Issue by BillyRayPreachersSon** [ember-intl/ember-intl#1926]
## The problem

I'm attempting to upgrade our Ember 3.24 project to 3.28 - which is a slow process given the size of the codebase.

One of the steps prior to the actual upgrade  is to reduce outdated `ember-cli-babel` warnings - which is why I'm trying to upgrade `ember-intl`. These warnings show as we're currently on `4.1.0` (which, interestingly, doesn't seem to exist as a tag in this repo - but that's not an issue for us).

I bit the bullet and went from `4.1.0` to `5.7.0` (the last supported version on Ember 3.24).

Upon starting my Ember server, I get an error `Cannot read property 'paths' of undefined`, with this stack trace:
```
  - broccoliBuilderErrorStack: [undefined]
  - code: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Cannot read property 'paths' of undefined
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Cannot read property 'paths' of undefined
  - name: TypeError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: TypeError: Cannot read property 'paths' of undefined
    at Class.cacheKeyForTree (/Users/dan.nye/new/Documents/code/platform/node_modules/ember-intl/index.js:47:32)
    at traverseAddons (/Users/dan.nye/new/Documents/code/platform/node_modules/ember-cli-addon-guard/lib/utils/review-project.js:54:66)
    at traverseAddons (/Users/dan.nye/new/Documents/code/platform/node_modules/ember-cli-addon-guard/lib/utils/review-project.js:76:13)
    at traverseAddons (/Users/dan.nye/new/Documents/code/platform/node_modules/ember-cli-addon-guard/lib/utils/review-project.js:76:13)
    at traverseAddons (/Users/dan.nye/new/Documents/code/platform/node_modules/ember-cli-addon-guard/lib/utils/review-project.js:76:13)
    at Object.reviewProject [as default] (/Users/dan.nye/new/Documents/code/platform/node_modules/ember-cli-addon-guard/lib/utils/review-project.js:28:5)
    at Class.included (/Users/dan.nye/new/Documents/code/platform/node_modules/ember-cli-addon-guard/index.js:35:49)
    at Class.superWrapper [as included] (/Users/dan.nye/new/Documents/code/platform/node_modules/core-object/lib/assign-properties.js:34:20)
    at /Users/dan.nye/new/Documents/code/platform/node_modules/ember-cli/lib/broccoli/ember-app.js:629:15
    at Array.forEach (<anonymous>)
```

## The diagnosis

Adding in some logging, it appears that when [`ember-cli-addon-guard`](https://github.com/dgeb/ember-cli-addon-guard) tries to call `ember-intl`'s `cacheKeyForTree` method, an error is thrown because `this.package` is not defined (it's only set if `ember-intl`'s `included` method is called first).

Use of `this.package` in `cacheKeyForTree` seems to have crept in with `ember-intl` `4.2.1` - and is still referred to in the newest version, `7.0.6`.

## Reproduction steps

I've tried on our setup:
* `ember-cli-addon-guard@0.2.1`
* `ember-cli@3.24.0`
* `ember-source@3.24.7`
* `ember-intl@5.7.0`
* `node@14.19.0`

I've also tried the same but with our target Ember upgrade versions:
* `ember-cli@3.28.6`
* `ember-source@3.28.12`

I've also tried using out-of-the-box LTS versions of Ember and Node:
* `ember-cli-addon-guard@0.2.1`
* `ember-cli@5.8.1`
* `ember-source@5.8.0`
* `ember-auto-import@2.8.1`
* `ember-intl@7.0.6`
* `node@20.17.0`

In all cases, running `ember s` will throw the above error.

## Where to go from here

I'm trying to work out which addon is at fault here - `ember-intl` or `ember-cli-addon-guard`. I'm leaning towards `ember-intl` being the culprit, as neither https://rfcs.emberjs.com/id/0090-addon-tree-caching/ nor https://ember-cli.com/api/classes/addon#method_cacheKeyForTree state that `included` _should_ be called before `cacheKeyForTree` in order for `cacheKeyForTree` to work.

We really don't want to fork `ember-intl` to fix this for `5.7.0`, nor do we want to fork `ember-cli-addon-guard` to add an extra call to `included` just for `ember-intl`. We also don't want to remove `ember-cli-addon-guard`, as it does a great job of protecting us from unpredictable behaviour with version mismatches.

Ideally, we'd love to see a fix backported to the 5.x releases. but I understand that isn't likely to be a priority. Regardless, I think that this is an issue worth raising so others could benefit even on the 7.x releases if they also wish to use `ember-cli-addon-guard`

**Comment by ijlee2** [comment]
Hi, @BillyRayPreachersSon. Thanks for working on updating your Ember project and reporting an issue.

Due to lack of time and knowledge with previous versions of `ember-intl`, I can only support issues with `ember-intl@>=6` and `node@>=18`. Ensuring compatibility with third-party addons is something I can't support, and needs to be checked by the end-developer through their CI instead.

To help with updating Ember and `ember-intl`, I recommend that you remove `ember-cli-addon-guard` first. Afterward, you can introduce [`ember-cli-dependency-lint`](https://github.com/salsify/ember-cli-dependency-lint), or use the "deduplicate" and "resolutions" features from your package manager (the exact names and methods can differ), to ensure that only 1 version of a package is installed whenever possible.

I haven't heard of `ember-cli-addon-guard` before. I noticed that it neither reached a stable version nor has been maintained in the last 5 years (i.e. it was [never proven via CI to work beyond `ember-cli@3.8` and `node@10`](https://github.com/dgeb/ember-cli-addon-guard/blob/v0.2.1/package.json#L41)). So I think removing this now will help you maintain your project more easily in the near future.

**Comment by BillyRayPreachersSon** [comment]
Thanks @ijlee2 - I shall switch to using `ember-cli-dependency-lint` instead.
