### ISSUE TITLE
Support sideloading of CLDR data

### ISSUE THREAD

**Issue by mjuniper** [ember-intl/ember-intl#268]
For apps that need to support many languages, sideloading the CLDR data would be great.

**Comment by buschtoens** [comment]
In order to support this, we essentially just need to do what we already do with the regular translations and `this.opts.publicOnly`:

https://github.com/ember-intl/ember-intl/blob/c92422d416de65db3fb70f68c57fec9b782dc40c/index.js#L93-L144

Then defuse the warning here:

https://github.com/ember-intl/ember-intl/blob/c92422d416de65db3fb70f68c57fec9b782dc40c/addon/hydrate.js#L13-L43

And document for users that they now not only need to call `addTranslations`, but also `addLocaleData`:

https://github.com/ember-intl/ember-intl/blob/c92422d416de65db3fb70f68c57fec9b782dc40c/addon/services/intl.js#L161-L173

We can't repurpose the `publicOnly` option, as this would be a breaking change for users of it. Any suggestions for a new option name?
