### ISSUE TITLE
allow parametrizing `t` with components

### ISSUE THREAD

**Issue by Dremora** [ember-intl/ember-intl#428]
- [x] I am on the [latest](https://github.com/jasonmit/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/jasonmit/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 2.7.0
- Ember CLI Version: 2.11.0
- Ember Intl Version: 2.19.0
- Browser(s): Chrome
- Node Version: 7.3.0

### Steps to Reproduce

I'm trying to parametrize a localizable string with a relatively complex piece of UI which should be injected in the middle of a string. I've tried the following:

```
{{t "timeline.previous_value" value=(component "status-pill"
    label=old.value
    type=old.type
  )
}}
```

This, however, renders as `[object Object]`.
I've looked into what `component` helper does, and it indeed simply returns a plain object (which I guess gets interpreted correctly by Glimmer).
I can't think of any other solution apart from splitting the string into two, which will be very confusing for the translators. It would be nice for ember-intl to correctly handle components passed as parameters.

**Comment by jasonmit** [comment]
One day I would like to support something like this, but currently I don't know of a path forward that would allow for this.

Related https://github.com/jasonmit/ember-intl/issues/102

**Comment by vvohra** [comment]
The way I do solve this problem is use placeholders for arguments, use regex split the translated string, and render the it in parts.

Example:
ICU String: "Hello what is your {name}" translated might be: "bla bla {name} blah bla" in other language.

For each argument I pass its own name, so like: name=`{name}`

Then the translated string returned from message formatter is: "bla bla {name} blah bla"

Then I split the string as so: ["bla bla ", "{name}", " blah bla"]

I render each array element. If the element is one that needs to be replaced with a component (I'm skipping over lots of internal needed bookkeeping for this description), I just render the component.

I could look into making this an addon or something, but I'd have to add lots of more tests to confirm it's stable. I am concerned with perf because of regex and string splitting, but, at least it works!

**Comment by jasonmit** [comment]
Closing as this is unlikely to be supported anytime soon.  Considerable amount of work would go into converting the t-helper to a component and that would introduces limitations (i.e., passing the result of the helper around expecting it to be a `string`/`String.safeString`).

**Comment by allthesignals** [comment]
We use https://github.com/FortAwesome/ember-fontawesome for icons (`<FaIcon @icon="external-link-alt"/>` to indicate a hyperlink, for example), but it looks like there isn't a straightforward way around this.

@vvohra did you find that your solution worked in the long run?
