### ISSUE TITLE
Intl polyfill in vendor.js file

### ISSUE THREAD

**Issue by Turbo87** [ember-intl/ember-intl#493]
Right now if you use `autoPolyfill: true` the addon will put all the Intl polyfill files into the `public` tree and load them by putting separate `<script>` tags for each of the files (one for the polyfill itself and for each locale another one) in the `index.html` file. This results in quite a few script loads on startup which is obviously not ideal.

One alternative option is using polyfill.io, but for some users that might not be a good option as it depends on a third-party service without any availability guarantees.

Another good option to prevent these script loads would be to add the polyfill to the generated `vendor.js` file. We could for example support something like `autoPolyfill: 'vendor'` and in this case we would bundle it automatically without the need for the `<script>` tags which would potentially improve pageload times. At @simplabs we currently have an app which uses this approach through a monkey patched solution and it seems to work quite well.

One thing I haven't tried yet is whether the locale-dependent files of the polyfill all need to be loaded upfront or if they could be loaded async too like it's possible for the translations.

/cc @jasonmit

**Comment by jasonmit** [comment]
I'm in favor of adding additional strategies for loading the polyfill.

> One thing I haven't tried yet is whether the locale-dependent files of the polyfill all need to be loaded upfront or if they could be loaded async too like it's possible for the translations.

Shouldn't be a problem.

**Comment by jasonmit** [comment]
I've extracted out the polyfill into it's own separate addon so it's not coupled to ember-intl.

https://github.com/ember-intl/polyfill/commit/c530a0c7c33d6ae2d2845155b0efb197af270fa3 is the working branch right now that will resolve this.  Need to figure out how I'm going to import individual locales and also support vendoring the entire intl polyfill with all the data (for those that don't care about payload size i.e, intranet apps).

I've also added the ability to force the polyfill to overwrite the global Intl API.  Useful if you want consistency across browsers since some browsers vary slightly in the CLDR dataset they use.  In Node, might be useful to always use the complete polyfill since precompiled builds of Node typically only contain en-us.

**Comment by jasonmit** [comment]
https://github.com/ember-intl/polyfill#vendorbundle-intl-polyfill resolves this.  Support for this within ember-intl will land soon.  Will close once I have a version cut.

**Comment by Turbo87** [comment]
@jasonmit what we are doing now is this:

we ship the Intl polyfill unconditionally in the `vendor.js` file (we should decide whether we ship it or not via the new `targets.js` feature of Ember CLI), but we do not bundle the `intl/locales/*.js` files.

in our `loadAndSetLocale(locale)` method we check if `window.Intl === window.IntlPolyfill` and in that case load the correct `intl/locales/${locale}.js` in parallel to loading the translation JSON file.

previously we had been bundling all of the polyfill locales in the `vendor.js` file and the change to the above strategy dropped almost 400 KB (before gzip) from our `vendor.js`.
