### ISSUE TITLE
this.get('intl').setLocale('en-us'); in addon

### ISSUE THREAD

**Issue by broerse** [ember-intl/ember-intl#515]
Hi,

I managed to add `ember-intl` to my addon. If the application does not use `ember-intl` but uses my addon I like to set this.get('intl').setLocale('en-us') if locale is ''

Is there some Example or Doc on where and how I should do this.

Thanks

- Martin

**Comment by broerse** [comment]
You can see my addon first try here. https://github.com/martinic/ember-cli-markdown-editor/blob/master/addon/components/markdown-editor.js#L181

When I do this in `init` and not `didInsertElement` it does not work. You can run the Dummy App (`ember s`) to see the warnings like `WARNING: [ember-intl] translation: 'markdown-editor.formats.heading.tooltip' on locale: '' was not found.`

Oddly everything translates fine.

**Comment by jasonmit** [comment]
> If the application does not use ember-intl but uses my addon I like to set this.get('intl').setLocale('en-us') if locale is ''

I think the text got cut off - can you clarify the end of that sentence.

**Comment by broerse** [comment]
> if locale is ''

It is not cut off but the checking for `''` comes from the warning `WARNING: [ember-intl] translation: 'markdown-editor.formats.heading.tooltip' on locale: '' was not found.`

**Comment by jasonmit** [comment]
@broerse okay I understand now.  Thanks - I will look into this.

**Comment by jasonmit** [comment]
Okay so ember-intl is behaving as expected here.  At the time of render, the locale was not set and you trigger the locale change after render, in `didInsertElement`, causing an immediate double render - which is why the translations are there after you see the warning.

I recommend you create an instance initializer within your addon to set a locale if the locale is unset.

https://guides.emberjs.com/v2.0.0/applications/initializers/#toc_application-instance-initializers

**Comment by broerse** [comment]
I don't like the repeating locale=_local but if it is the default for addons I can live with it ;-) 

I tried your code end it does not work. See `setlocale` branch:

https://github.com/martinic/ember-cli-markdown-editor/commit/dfd9569094952fc9894855d7acfc69f8bc247bee

The warning is now changed from '' to 'en-us' was not found:
`WARNING: [ember-intl] translation: 'markdown-editor.formats.heading.tooltip' on locale: 'en-us' was not found.`

And the tooltip is now saying `Missing translation: markdown-editor.formats.heading.tooltip`

I hope you can take a look.

**Comment by jasonmit** [comment]
Reopening as a reminder to follow up.

**Comment by jasonmit** [comment]
https://github.com/ember-intl/ember-intl/pull/516 will resolve the warnings.  Intl hydrates the translations that have been bundled into the application when the service is first initialized.  Since you're an addon that never calls injects `intl` it's not instantiated until rendering occurs (triggered by the `t` helper in your template).  Which causes rendering the take place, intl then is instantiated and attempts to hydrate itself with the bundled translations, and notifies the `t` helper to re-render.

This change avoids that from happening by just eagerly instantiating the service during app initialization.  

Also - if you see warnings in your unit tests (initializers do not run for unit tests), be sure to just invoke setLocale before rendering.

**Comment by broerse** [comment]
Many thanks. Just tried and `2.29.1` solves it.

**Comment by broerse** [comment]
It now also works without adding locale=_locale if you do an init in the component like this:

```
  /*
   * Set locale to `en-us` if it is not set by the application
   */
  init: function() {
    this._super(...arguments);
    if(!this.get('intl').get('locale')) {
      this.get('intl').setLocale('en-us');
    }
  },
```
Is the ` if(!this.get('intl').get('locale')) {` correct and do you want me to write PR for the addon Doc?

**Comment by jasonmit** [comment]
I would recommend not setting app state from within your addon (setting the app's locale).  I'd continue to recommend passing it as an attribute to each of the `t` helpers.
