### ISSUE TITLE
intl-polyfill: show a warning for unknown locales

### ISSUE THREAD

**Issue by jrburke** [ember-intl/ember-intl#573]
_Edit: actual enhancement suggestion here: https://github.com/ember-intl/ember-intl/issues/573#issuecomment-390351334_

---

- [x] I am on the [latest](https://github.com/jasonmit/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/jasonmit/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: Ember 2.18.2
- Ember CLI Version: 2.18.2
- Ember Intl Version: 2.33.2
- Browser(s): n/a, build issue
- Node Version: 8.10.0

### Steps to Reproduce

```
ember build --environment=production
```

Using this `config/ember-intl.js`:

```javascript
const env = require('./environment');
module.exports = function (environment) {
    return {
        locales: [
            "de-de",
            "el-gr",
            "en-au",
            "en-gb",
            "en-us",
            "no-no",
        ],
        baseLocale: null,
        autoPolyfill: true,
        disablePolyfill: false,
        publicOnly: true,
    };
};
```

`dist/assets/intl/locales/no-no.js` is not written to dist.

6 of the 37 locales in total are missed, but I condensed this code to show the general shape of the issue. Complete set of missing ones:

* iw-il
* no-no
* vi-vi
* zh-cn
* zh-hk
* zh-tw

I tried tracing in the node debugger, and I can see broccoli-cldr-data writing out a no.js file, but I am not sure what then takes that information and writes out the files in the dist/ folder.

I am willing to debug further, but need some pointers as to what to look for, and why a particular locale might be dropped.

**Comment by jasonmit** [comment]
As of now, CLDR data cannot be sideloaded so that data is bundled into the dist.  Track #268 for progress on that, it's been asked for once but I simply haven't prioritized it above other work.

The translations however can be side-loaded and should be written to `locales`.  Do you have translations for `no-no` and the other missing locales?

**Comment by jrburke** [comment]
I'm fine if the CLDR data cannot be sideloaded, it just ends up that the index.html has script tags for the locales above, but not the actual .js files in the output for that CLDR data.

I do have the localized strings for all the locales, and those can be loaded fine, just trying to figure out why the `dist/assets/intl/locales/no-no.js` file does not end up in the output.

What piece of code takes the CLDR data and creates those dist files? If I know that, then I can try some debugging around that code.

**Comment by jasonmit** [comment]
> What piece of code takes the CLDR data and creates those dist files?

Ah, sorry I misunderstood your question originally because I assumed you were referring to the CLDR files but it looks like you're referring to the intljs polyfill locale data.

https://github.com/ember-intl/ember-intl/blob/2273bbe1269e125135ab5da9c3077e9dd1280e7b/lib/broccoli/intl-polyfill.js#L35-L48 are the lines that you're asking for.

Looks like `no-no` should be `nb-no`.  `nb` is the language and `no` is the locale.

List of supported locales:
https://github.com/andyearnshaw/Intl.js/tree/master/locale-data/jsonp

**Comment by jrburke** [comment]
I am still sorting through a solution, but I think I have something working where I modify the locales I set up in the `config/ember-intl.js` to match one that is in https://github.com/andyearnshaw/Intl.js/tree/master/locale-data/jsonp.

As for what to do for others, I can see generating a warning that mentions the mismatched locale, and a pointer to the list of locales in https://github.com/andyearnshaw/Intl.js/tree/master/locale-data/jsonp as the ones that are supported.

Suggesting a warning vs an error, since other locales could work, and in my situation, I still wanted to build/deploy for those other locales while I sorted out the problem ones. But I understand if generating an error would be preferred. Technically the build did not succeed with the given inputs.
