### ISSUE TITLE
Add `fallbackLocale`

### ISSUE THREAD

**Issue by Turbo87** [ember-intl/ember-intl#584]
Apparently the `baseLocale` option was removed for `ember-intl@3`, but this seemed like a quite useful option, which prevented users from seeing "missing translation" and instead at least showing e.g. the english version of the thing. 

I agree that `baseLocale` as a way to determine whether translations are missing was not ideal and it's good that that part got refactored, but I think having such a `fallbackLocale` option would still be valuable to a lot of projects.

@jasonmit are you open to bringing back such an option?

**Comment by jasonmit** [comment]
Assuming you're willing to load your English translations for everyone, `intl.setLocale(['fr-fr', 'en-us'])` would earn you similar behavior w/o the build time merge that used to happen.

**Comment by jasonmit** [comment]
`fallbackLocale` will naturally lead to the confusion.

* When to use this approach vs `setLocale([]);`
* communicating that it's only a build-time thing so async translations will not work as some might expect
* by defining a fallback do I need to not set a default locale

Those familiar with ember-intl may immediately be able to answer these but it adds friction for newcomers trying to get started.

I've been hoping to open up the build pipeline further that would make something like this possible w/o being a direct part of ember-intl.  Something a long the lines of preprocessor hook.  I'd rather invest there since it opens up more possibilities.

**Comment by Turbo87** [comment]
> When to use this approach vs setLocale([]);

I have never found a use for `setLocale([]);` before...

> async translations will not work as some might expect

I don't understand this. We are using async translation loading with the current `baseLocale` feature and it works very well.

> by defining a fallback do I need to not set a locale at app boot

that is a documentation issue that can easily be resolved

**Comment by jasonmit** [comment]
> I don't understand this. We are using async translation loading with the current baseLocale feature and it works very well.

External translation service.  Story becomes muddled as to what even is a fallback locale in the context of those loading their translations from an external API.

> that is a documentation issue that can easily be resolved

Yes and we can solve this issue with documentation once there is a story for extending the translation bundling process.  I see this as being a plugin to that without complicating the core API.

**Comment by jasonmit** [comment]
@Turbo87 I spent a little time digging into this tonight.  What are your thoughts on ember-intl invoking pre/postprocessTree hooks in ember-cli with the translation tree.  These two hooks should be all you need to implement.

```js
/* lib that does exactly what was previous done */
const mergeTranslations = require('./lib/merge-translations');

{
  name: 'merge-translations',
  /* work could also be done in preprocess, postprocess would be after the concatting of translation files and missing translation warning would have already happened */
  postprocessTree(type, tree) {
    if (type === 'translation') {
      return mergeTranslations(tree);
    }

    return tree;
  }
}
```

**Comment by Turbo87** [comment]
idk, I'm a little worried about extending an existing hook with different meaning. I'd probably use dedicated hooks just for `ember-intl`.

**Comment by riklaunim** [comment]
Another problem that a test now wants to use "en-us" which does not exist and "en" translation isn't considered for usage.

**Comment by jasonmit** [comment]
@riklaunim for tests you can set the locale of the service before your tests run.  Today, it defaults to `en-us` when unset.  Let me know if I'm misunderstanding your comment.

**Comment by riklaunim** [comment]
Yes, that's what I did. But it's kind of odd I can't set a default language yet en-us is the default.

Plus even when I haven en language it's not used for en-us.

**Comment by jasonmit** [comment]
> But it's kind of odd I can't set a default language yet en-us is the default.

https://github.com/ember-intl/ember-intl/blob/master/docs/integration-testing.md#setupintlhooks-locale makes this less painful.

> Plus even when I haven en language it's not used for en-us.

Negotiating the locale based on the data loaded into the service is something that would be an interesting feature.  Not something currently supported but not something I'm against adding.

**Comment by sbsurf** [comment]
I use `intl.setLocale([locale, "en"])`, but it doesn't seem to have the effect in this comment:

https://github.com/ember-intl/ember-intl/issues/584#issuecomment-399868684

If `locale` is `es`, for example, any missing `es` translations come up as empty, instead of falling back to the `en` translations.

Bring back `baseLocale` would be helpful. Or perhaps someone can help me get the suggested solution to work?

**Comment by jasonmit** [comment]
Can you open a separate bug for the fallback issue you described?

**Comment by jasonmit** [comment]
@sbsurf awesome timing for that fix to land!  Open an issue if you find it doesn't solve your issue after bumping to 3.5.0.

**Comment by jacobq** [comment]
FWIW, I have a use case for having a fallback (permanent default) locale that I don't think has been mentioned here yet. I have a number of "locale-less" strings, which are actually IDs like `company_1` that should be translated to the same thing in every locale (say, "Google").

In `ember-i18n` I was able to provide translation files in `js` rather than JSON so could just merge those shared values into every translation file, but `ember-intl` doesn't seem to offer a way to do this. Now it seems that I need to wrap access to the setter for `locale` (e.g. there is a select element that allows the user to change the language/locale) to ensure that it is always in array form and includes the default locale (perhaps `en` or perhaps a custom `common` one, if allowed). This seems like a lot more fuss than necessary to me. Is there another approach that I should be using instead? (e.g. trying to handle this in the missing translation hook)

**Comment by jasonmit** [comment]
@jacobq thank you for the feedback.

I'm not against bringing back fallback locale.  I think it would be a relatively easy feature to bring back and could land as part of the current 4.0 beta.
