### ISSUE TITLE
Support for translations in resource bundle files (.properties)

### ISSUE THREAD

**Issue by makepanic** [ember-intl/ember-intl#595]
Hi,
would you be open to add support for providing ember-intl translations via a [resource bundle files](https://www.jetbrains.com/help/idea/resource-bundle.html#editing)?

If ember-intl does this, editors like intellij provide an improved editor for translating keys:

![https://www.jetbrains.com/help/img/idea/2018.2/bundleEditor.png](https://www.jetbrains.com/help/img/idea/2018.2/bundleEditor.png)

It works if the editor finds suffixed `.properties` files in a directory. 
It'll merge them into a resource bundle and use a special editor for editing.

From what i can tell it should be possible to support these as the format is very similar to the yaml/json that ember-intl already supports.

The only open question would be how ember-intl detects the locale properties file.
As far as I can tell, intellij requires the format `.*_[a-z].properties`. 

One could solve this by transforming any properties file, using a locale suffix, into a JSON translation:

```
- i18n_de.properties
- i18n_en.properties
```

This could cause issues if a user creates multiple files with the same suffix, e.g. 

```
- app_de.properties
- shop_engine_de.properties
```

One could solve this by requiring a specific prefix for each properties file or maybe add a feature to merge multiple translations in the same language.

**Comment by jasonmit** [comment]
I truthfully don't know a whole lot about this.

@Turbo87 I believe you use IntelliJ, can you make a call here :)

**Comment by Turbo87** [comment]
I'll look into it when I'm back from vacation :)

**Comment by buschtoens** [comment]
Would it make sense to take a step further back and provide an API to build custom translation assemblers, also taking #401 into account maybe?

**Comment by jasonmit** [comment]
@buschtoens definitely.

Some of that work landed with `treeForTranslations` hook.  As long as you transform the resource bundles into yaml/json files within the hook things should *just work*.

**Comment by buschtoens** [comment]
The [`properties` package](https://github.com/gagle/node-properties) seems like an easy solution to parse `.properties` files. Together with [`treeForTranslations(tree)`](https://github.com/ember-intl/ember-intl/blob/0eda54c7a1784ebca54b4e72e134bd53e9de2457/docs/addon-support.md#advanced-usage-treefortranslations) one can write an addon that combines both.

`treeForTranslations(tree)` only receives the _addon's own_ translation tree though. If I would write such an addon that handles a new file format, I would want it to be able to mutate the translations tree that was created by ember-intl.

I think it would be sufficient to either pass `projectTranslations` or the `WatchedDir` to the individual addons, so that they can use the same input tree to generate translations from:

https://github.com/ember-intl/ember-intl/blob/c92422d416de65db3fb70f68c57fec9b782dc40c/lib/broccoli/build-translation-tree.js#L11-L29

```js
 function buildTranslationTree(project, inputPath, treeGenerator) { 
   const projectTranslations = path.join(project.root, inputPath); 
   const projectTranslationsTree = fs.existsSync(projectTranslations) ?
     new WatchedDir(projectTranslations) : null;
   const trees = []; 
  
   processAddons(project.addons, trees, treeGenerator, projectTranslationsTree); 
  
   if (projectTranslationsTree) { 
     trees.push(new WatchedDir(projectTranslations)); 
   } 
  
   return funnel( 
     mergeTrees(trees, { 
       overwrite: true 
     }), 
     { 
       include: ['**/*.yaml', '**/*.yml', '**/*.json'] 
     } 
   ); 
 } 
```

Since only `.yaml`, `.yml`, and `.json` files are handled there would not be any [key collision](https://github.com/ember-intl/ember-intl/blob/0eda54c7a1784ebca54b4e72e134bd53e9de2457/docs/addon-support.md#overriding-translations) as `.properties` files are not understood by ember-intl itself.

I think this is not _ideal_ yet, but it's an easy, non-breaking change.

I don't know yet, what I would want an ideal API to look like, but as an addon creator, I would like to get more control over the [`TranslationReducer`](https://github.com/ember-intl/ember-intl/blob/c92422d416de65db3fb70f68c57fec9b782dc40c/lib/broccoli/translation-reducer.js) as well, so that I could implement custom filter, map and override logic.

**Comment by buschtoens** [comment]
Also relevant https://github.com/ember-intl/ember-intl/issues/401#issuecomment-316629409:

> `treeForTranslations` which will be a hook to write programmatically mutate the translation tree for the immediate addon _not_ the host's translations!
> 
> `preProcessTranslationTree`/`postProcessTranslationTree` hook that will be a chance for any addon to do whatever they want to the hosts translation tree.

<sup>`treeForTranslations` is implemented already by now</sup>

**Comment by makepanic** [comment]
Can confirm that the `treeForTranslations` addon hook isn't really usable to transform translations for the consuming app.

I think a new hook for this kind of feature would be great as it'll allow developers to implement support for various other translation formats like e.g. [XLIFF](https://en.wikipedia.org/wiki/XLIFF)

**Comment by jasonmit** [comment]
Even though you're not provided the project's translations, you should still be able to read your host parents translations using traditional `fs` APIs and return your own broccoli tree containing the transformed translations.  If you need an example, let me know.

I've done similar strategies in the past w/o any problems but this isn't exactly a well traveled path so let me know if you run into anything specific.

**Comment by RuslanZavacky** [comment]
@jasonmit maybe if you have an example it would be great to have one.. as my case is we have a lot of apps and a lot of addons inside another addons. Translation files will be kept close to components on their level and need to be combined together. If you have an example, that would be great :) if not, no worries, I am anyway digging into it now 🙇

**Comment by jasonmit** [comment]
@RuslanZavacky example of the hook: https://github.com/ember-intl/ember-intl/issues/1464#issuecomment-734009962
