### ISSUE TITLE
Cannot build, due to test-support trying to be bundled with my app?

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-intl/ember-intl#599]
- [ x ] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [ x ] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 49e58e45604bd63ac1001cb491195c032c050053
- Ember CLI Version: 0f9d15d011fd9adb4c2a8db52e44bf5d74679631
- Ember Intl Version:  3.1.1
- Browser(s): n/a
- Node Version: 8.11.3

### Steps to Reproduce

Clone this repo: https://gitlab.com/NullVoxPopuli/emberclear/

run `cd packages/frontend; yarn build:production`

Get error:

```
Build failed.
Build Error (Bundler)

bundleForPath("ember-intl/test-support/-private/pick-last-locale.js") returned tests" but the only configured bundle names are app
```

**Comment by jasonmit** [comment]
Unclear to me why you're hitting this.  I'm also using 3.1.1 in prod and haven't encountered this.  May be an issue with another one of your dependencies (treeShaking perhaps?).  I'll need to spend time looking into what the cause is but it's likely outside of ember-intl's control here.

@buschtoens any ideas?

**Comment by NullVoxPopuli** [comment]
but also, @ef4 said it was an issue with ember-auto-import https://github.com/ef4/ember-auto-import/issues/105

which has a known issues with canary.

**Comment by jasonmit** [comment]
Okay I'll treat this as a dependency bug and will keep an eye out for the solve.  

Given what we are leveraging auto import for(lodash util methods), we can consider removing it temporarily.

**Comment by ef4** [comment]
@NullVoxPopuli yes, https://github.com/ef4/ember-auto-import/issues/105 was breaking your situation. But there is no other known issue with canary -- the one you reported a long time ago was resolved.

**Comment by scudmissile** [comment]
I don't think this is an issue with ember-cli canary, as I'm encountering it while using ember-source@3.1.4, ember-cli@3.1.4, and ember-intl@3.1.1. I was able to work around it by downgrading from version 1.2.11 to 1.2.10 of ember-auto-import. 

I also commented on https://github.com/ef4/ember-auto-import/issues/110 since I saw that other people had filed an issue that matched mine there.

**Comment by ef4** [comment]
At this point, I don't have any known ember-auto-import bugs that would be relevant to ember-intl, so if you are still having trouble please file a new issue.

**Comment by jasonmit** [comment]
Fix upstream in ember-auto-import resolves the original issue, feel free to reopen if you're still having issues after upgrading.  Thanks @ef4!
