### ISSUE TITLE
Loading async translations with JSONP instead of XHR

### ISSUE THREAD

**Issue by estshy** [ember-intl/ember-intl#607]
I have a website running on multiple domains with several languages, which are loaded asynchronously depending on context. I am working on improving application boot time and I can see that loading of translations through XHR is currently a bottleneck as such request is blocking everything else (deferReadiness used). I was wondering whether it would not be possible to go with JSONP instead. It would allow to start loading of the translations even before ember was be fetched. 

I also had a few difficulties with proper handling on fingerprint on translation files as ember does not provide access to fingerprint at runtime. 

Why does ember intl comes with XHR mechanism built in? Were there any advantages that I am overlooking right now?

**Comment by buschtoens** [comment]
> Why does ember-intl comes with XHR mechanism built in? Were there any advantages that I am overlooking right now?

ember-intl doesn't come with XHR built in. It is entirely agnostic to how you load translations, if you don't bundle them in.

The docs on [asynchronously loading translations](https://github.com/ember-intl/ember-intl/blob/2.x/docs/asynchronously-loading-translations.md) demonstrate that:

```js
// app/routes/application.js
export default Ember.Route.extend({
  intl: Ember.inject.service(),
  async beforeModel() {
    let translations = await fetch('/api/translations.json');
    this.get('intl').addTranslations('en-us', translations);
    this.get('intl').setLocale('en-us');
  }
});
```

[`fetch`](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) is native browser API. Instead of using `fetch` to asynchronously load the translations during app boot, you could instead inject `<script>` tags into your HTML, that load your translations in a JSONP manner.

Depending on your supported browser targets, you could also use [`<link rel="preload" href="/api/translations.json" as="fetch">`](https://stackoverflow.com/a/46536558) to preload the JSON request on page load.

**Comment by estshy** [comment]
@buschtoens Unfortunately the approach with link preload as fetch doesn't work at the moment. I am not sure whether preload as fetch is already widely supported.

![image](https://user-images.githubusercontent.com/5459938/45482059-5880c900-b74d-11e8-9a06-22ed17c19191.png)

```
<link rel="preload" href="http://localhost:4200/assets/translations/pl-pl.json" as="fetch">
```

```
    fetch(path)
    .then(response => response.json())
    .then((response) => {
      container.register('website:translations', response, {
        instantiate: false
      });
    })
    .finally(() => container.advanceReadiness())
```

**Comment by buschtoens** [comment]
> You can see on screenshot below that first request has a type "json" instead of fetch.

Try setting the correct `Accept` / `Content-Type` request header.

> Unfortunately the approach with link preload as fetch doesn't work at the moment. I am not sure whether preload as fetch is already widely supported. 

Should be correctly supported in Chrome. 🤔 
But it's currently disabled in Firefox. IE and other browsers don't have it at all.

Anyhow, since this is not widely supported _yet_, you might wanna go a different route any how.

> On top of that, I can not access service in any ember initializer.

You can in _instance_ initializers.

> When it comes to ember-cli-ifa, it has its own disadvantages. I have to either put full assetsmap on my index.html, which is a real concern when there are many assets, or load it asynchronously during startup, which adds extra request to boot time.

That's true. I just wanted to show different techniques, how you can resolve files to their fingerprinted counter parts. 😊 

Proper JSONP sounds like the best solution. One disadvantage of JSONP to JSON is that JSON can be parsed significantly faster than JS. Maybe the JSON object should be stringified and then parsed in the JSONP code. Would need proper benchmarking though.

**Comment by estshy** [comment]
>> On top of that, I can not access service in any ember initializer.
> You can in instance initializers.

In instance initializers I can not defer application readiness, which means the application would start in the same time translations were fetched and user would see a flash of untranslated content.

**Comment by jasonmit** [comment]
> In instance initializers I can not defer application readiness

Can this work take place within your application route's lifecycle hooks (beforeModel, model, afterModel) instead?

**Comment by estshy** [comment]
> > In instance initializers I can not defer application readiness
> 
> Can this work take place within your application route's lifecycle hooks (beforeModel, model, afterModel) instead?

It can not as I have internationalised routing which needs to be setup in instance initializer. I can not add new routes at application runtime. ;)

**Comment by estshy** [comment]
> Unsure what the means. You're using the translations from ember-intl to create paths?
Yes, that's exactly what I meant. I am using intl translations for creating different paths on websites. For instance, on polish domain I have contact form access by /kontakt and on english domain I have contact page exposed on /contact.

`<script>self.translationDeferred = fetch('...');</script>`

When it comes to this solution then I agree it will work around the issue, though I have a few more difficulties with it. 

- Fetch might need polyfill
- I need information about which language should I fetch and this information is passed from backend to frontend through <meta name="config/environment" />. If I want to access it outside of ember then I will have to parse it in 2 places (ember and index.html). Currently I have configuration interpreted through flow defined in initializers

**Comment by jasonmit** [comment]
> I need information about which language should I fetch and this information is passed from backend to frontend through .

I thought the intent of this was to start loading the translations before/while your app code is fetched.  At what point do you have enough knowledge to fetch the translations?  That's the part where you would go and fetch the requests.

> Fetch might need polyfill

It's an example, feel free to use whatever you want to fetch the data (XHR?).
