### ISSUE TITLE
Integrate @ember-intl/polyfill

### ISSUE THREAD

**Issue by buschtoens** [ember-intl/ember-intl#638]
@jasonmit I see that you have started work on [`@ember-intl/experimental-polyfill`](https://github.com/ember-intl/experimental-polyfill). Can you remember what still needs to be done to drop the `experimental` part and start using it as a dependency of `ember-intl`. 😄 

Relates to:
- Support sideloading of CLDR data #268
- intl-polyfill: show a warning for unknown locales #573
- "autoPolyfill" should just work in fastboot mode #439
- Intl polyfill in vendor.js file #493
- Force usage of polyfill #519

**Comment by jasonmit** [comment]
This work was based off of working in tandem with the ember-intl experimental branch.  It would take a light refactor to get working against master.

Ideally, ember-intl would lookup the `@ember-intl/polyfill` addon and provide it with some context (locales that need to be bundled based on the translations in the host app).  https://github.com/ember-intl/experimental-polyfill/blob/master/index.js#L34 is how I sort of rigged that to work originally.  Open to revisiting that strategy.

**Comment by jasonmit** [comment]
This is next on my to-do list now that we cut 4.0 latest.  Ember-intl 5 will no longer ship with the Intl polyfill and I'll recommend installing future add-on to fill the gap for users that need it for either consistent output across browsers or legacy browser support.

**Comment by jasonmit** [comment]
Feature request for polyfill to support lazy loading: https://github.com/ember-intl/ember-intl/issues/844

**Comment by jasonmit** [comment]
Decided to no longer support polyfilling.  There are many strategies and they vary between projects - so I'm going to leave that up to the users to decide.  I've documented the browser/runtime requirements here: https://github.com/ember-intl/ember-intl/blob/master/tests/dummy/app/pods/docs/getting-started/runtime-requirements/template.md

**Comment by timiyay** [comment]
@jasonmit does this mean the necessary polyfill files won't be included in our Ember builds anymore?

We have some conditional polyfill logic that uses the poyfill JS files that `ember-intl` includes in our builds, like `/assets/intl/intl.min.js`, `/assets/intl/locales/en.js`, etc.

Will there be a breaking change where these files are no longer available to us? I'll need to schedule some maintenance of our apps accordingly.

**Comment by jasonmit** [comment]
> @jasonmit does this mean the necessary polyfill files won't be included in our Ember builds anymore?

In the near future 5.x release we are moving to an entire native approach Intl API approach.

ember-intl will assume APIs such as `Intl.NumberFormat`, `Intl.DateTimeFormat`, [`Intl.RelativeTimeFormat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RelativeTimeFormat) and [`Intl.PluralRules`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/PluralRules) are all available at runtime.

If you're targeting browsers that do not yet implement these APIs, you will either want to stay on 4.x or implement a polyfill strategy if you don't yet have one.

I can see the community, or myself, filling the gap with a polyfill addon.  However, as of now that isn't a majority priority of mine since my time is limited and I'd rather focus on modernizing this addon - as it's been falling behind as the native APIs have evolved.

**Comment by timiyay** [comment]
Thanks for the extra details, that lets me plan our next moves.
