### ISSUE TITLE
Can't access intl service in addon tests and dummy app

### ISSUE THREAD

**Issue by herzzanu** [ember-intl/ember-intl#906]
I'm extending the intl service in my addon but when I try to access it in the tests I can only access the original service. However it works when consuming it in the app. It also worked when I had it extended in the app so the issue is only in the addon.

```javascript
import Service from 'ember-intl/services/intl';

export default Service.extend({
  currentLocale: 'en'
});
```

### Environment

- Ember Version: 3.10.1
- Ember CLI Version: 3.10.0
- Ember Intl Version: 3.5.2
- Browser(s): All
- Node Version: 10.15.3

### Steps to Reproduce

Extend the intl service in the addon and add a simple attribute like `currentLocale: 'en'`. Try to access that in the dummy app. Also try to access it in an integration test like

```javascript
let service = this.owner.lookup('service:intl');
service.currentLocale
```

Also accessing the `intl` service in unit tests work only like this

`import IntlService from 'my-addon/services/intl';`
`let service = IntlService.create(this.owner.ownerInjection());`

**Comment by jasonmit** [comment]
ember-intl does not do anything out of the ordinary in registering the service.  You may need to tell ember-cli to use your addon's app tree over ember-intl's app tree.  Right now, it just sounds like my app tree is winning out.

That can be fixed in your addon by doing something like this:

```
// package.json
{
 ...
 "ember-addon": {
    ...
    "after": ["ember-intl"]
  }
}
```

If this doesn't resolve it, I'd need a working reproduction of the issue that I can clone and look at.

**Comment by herzzanu** [comment]
Thanks a lot, this was exactly the issue and it's now solved 🙇 Closing...
